id: D3012B542
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-11T09:50:37+00:00'
last_modified: '2022-05-26T12:22:59.135446+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    cca4:
      image_group_id: I1PD95882
      title: དཔལ་ཕྱག་ན་རྡོ་རྗེ་ལ་བསྟོད་པ།
      total_pages: 1379
      order: 37
      base_file: cca4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
