id: P839CCCD7
initial_creation_type: ocr
source_metadata:
  volumes:
    bfa393833a864baab2bb461216dbec76:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: དཔལ་ཕྱག་ན་རྡོ་རྗེ་ལ་བསྟོད་པ།
      total_pages: 1379
      volume_number: 37
